### ISSUE TITLE
/game/create returns number not string

### ISSUE THREAD

**Issue by taitfuller** [SE750-DART/nerds-oppose-society#60]
This is caused by util.digitShortCode() returning a number to game service createGame(). This service should be updated to return the game code as a string to the game controller

**Comment by Alxjlv** [comment]
@taitfuller it appears that this was originally passing a string through to the controller anyway?
![image](https://user-images.githubusercontent.com/44216323/117556305-7304cf00-b0bb-11eb-8d2e-44d1360333e3.png)

**Comment by taitfuller** [comment]
So it is! Hmmm what's going on there then 🤔 @RawiriHohepa  was encountering an issue where it was a number when testing the APIs but I'm not sure if I've seen it appear since then so may have resolved itself

**Comment by RawiriHohepa** [comment]
Okay looks like it's not a problem but only because it's only used in a string (`/${res.data}`). If it was sent as it is to /game/validate (which happens on the debugging BasicPage) then it would throw an error

It still very much returns as a number tho so not sure whats going on in the controller.
